spring.application.name=configserver
spring.cloud.config.server.git.uri=https://github.com/Shrey3489/Job-Application-microservice.git
spring.cloud.config.server.git.search-paths=Application-config
server.port=8888

